### ISSUE TITLE
Getting an error Cannot find module 'xbase'

### ISSUE THREAD

**Issue by rotaercz** [mtgjson/mtgjson#103]
I'm getting an error that looks like the following. Any idea how to fix this? Any help would be appreciated. I'm using WIndows 7. I can provide instructions on how to make it work on Windows if this part can be solved.

Error: Cannot find module 'xbase'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\mtgjson-master\mtgjson-master\build\buildSet.js:4:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by rotaercz** [comment]
I solved the above. However I'm getting the error:


/mtgjson-master/node_modules/tiptoe/index.js:21
                                throw args[0];
                                          ^
TypeError: Object #<Object> has no method 'gzipSync'
    at Function.createDoc (/mtgjson-master/shared/shared.js:667:38)
    at next (/mtgjson-master/node_modules/tiptoe/index.js:48:22)
    at Object._onImmediate (/mtgjson-master/node_modules/xutil/http.js:75:82)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by lsmoura** [comment]
I don't have a windows machine to test this... But it seems like an issue with "gzipping" the cache.

**Comment by lsmoura** [comment]
in line 667 change ```fs.writeFileSync(cachePath, zlib.gzipSync(pageHTML)); ``` to ```fs.writeFileSync(cachePath, pageHTML);```.

in line 638 change ```zlib.gunzip(fs.readFileSync(cachePath), this);``` to ```fs.readFile(cachePath, 'utf8', this);```

in line 497 change ```var urlHash = hash("whirlpool", targetUrl) + ".gz";``` to ```var urlHash = hash("whirlpool", targetUrl);```

I haven't actually tested this, but it should work.

**Comment by galaxyoyo** [comment]
In shared.js :
- Add `crypto = require("crypto"),` at the top
- Replace line 513 with `var urlHash = crypto.createHash("whirlpool").update(targetUrl).digest("hex") + ".gz";`
- Replace line 506 with `card.id = crypto.createHash("sha1").update(fullSet.code + card.name + card.imageName).digest("hex");`
- Run `npm install crypto` in the root folder (not in the build folder)

I tested this and it worked. However I didn't have the same error ... It told me that hash is not a function ...

**Comment by fenhl** [comment]
Receiving the original error on macOS.

@rotaercz: How did you solve the original error?
