### ISSUE TITLE
Throbber crash?

### ISSUE THREAD

**Issue by ShawnieBoy** [mtgjson/mtgjson#369]
On a first launch and going into Card Explorer, I'm usually getting this crash. Launching again doesn't crash.

```
Exception occurred in updating field 'angle' of object magic.ui.widget.throbber.ImageThrobber at timeline position 0.88249993
java.lang.RuntimeException: Unable to set the value of the field 'angle'
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:75)
        at org.pushingpixels.trident.TimelinePropertyBuilder$GenericFieldInfo.updateFieldValue(TimelinePropertyBuilder.java:368)
        at org.pushingpixels.trident.Timeline$Setter.onTimelinePulse(Timeline.java:158)
        at org.pushingpixels.trident.Timeline$Chain.onTimelinePulse(Timeline.java:252)
        at org.pushingpixels.trident.TimelineEngine$2.run(TimelineEngine.java:559)
        at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:215)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:73)
        ... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
        at magic.ui.helpers.ImageHelper.getCompatibleBufferedImage(ImageHelper.java:161)
        at magic.ui.widget.throbber.AbstractThrobber.getNextFrameImage(AbstractThrobber.java:145)
        at magic.ui.widget.throbber.AbstractThrobber.paintNextFrame(AbstractThrobber.java:125)
        at magic.ui.widget.throbber.AbstractThrobber.setAngle(AbstractThrobber.java:116)
        ... 9 more
Exception occurred in updating field 'angle' of object magic.ui.widget.throbber.ImageThrobber at timeline position 0.9214999
java.lang.RuntimeException: Unable to set the value of the field 'angle'
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:75)
        at org.pushingpixels.trident.TimelinePropertyBuilder$GenericFieldInfo.updateFieldValue(TimelinePropertyBuilder.java:368)
        at org.pushingpixels.trident.Timeline$Setter.onTimelinePulse(Timeline.java:158)
        at org.pushingpixels.trident.Timeline$Chain.onTimelinePulse(Timeline.java:252)
        at org.pushingpixels.trident.TimelineEngine$2.run(TimelineEngine.java:559)
        at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:215)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.pushingpixels.trident.TimelinePropertyBuilder$DefaultPropertySetter.set(TimelinePropertyBuilder.java:73)
        ... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
        at magic.ui.helpers.ImageHelper.getCompatibleBufferedImage(ImageHelper.java:161)
        at magic.ui.widget.throbber.AbstractThrobber.getNextFrameImage(AbstractThrobber.java:145)
        at magic.ui.widget.throbber.AbstractThrobber.paintNextFrame(AbstractThrobber.java:125)
        at magic.ui.widget.throbber.AbstractThrobber.setAngle(AbstractThrobber.java:116)
        ... 9 more
```

**Comment by ShawnieBoy** [comment]
Oops wrong board >.<
