### ISSUE TITLE
`Forbidden` when running python3 -m mtgjson4 -ac

### ISSUE THREAD

**Issue by hankinsoft** [mtgjson/mtgjson#373]
#### Description of Bug:

When trying to run the script:

`python3 -m mtgjson4 -ac`

It fails with 'forbidden' with the following output:

```
[INFO] 2019-06-13 08:41:30,510: Fetching from Scryfall with authentication
[INFO] 2019-06-13 08:41:30,520: Downloaded: https://api.scryfall.com/sets/ (Cache = True)
[INFO] 2019-06-13 08:41:30,521: Sets to compile: ['10e', '2ed', '3ed', '4bb', '4ed', '5dn', '5ed', '6ed', '7ed', '8ed', '9ed', 'a25', 'aer', 'akh', 'ala', 'all', 'ana', 'apc', 'arb', 'arc', 'arn', 'ath', 'atq', 'avr', 'bbd', 'bfz', 'bng', 'bok', 'brb', 'btd', 'c13', 'c14', 'c15', 'c16', 'c17', 'c18', 'c19', 'ced', 'cei', 'chk', 'chr', 'cm1', 'cm2', 'cma', 'cmd', 'cn2', 'cns', 'con', 'cp1', 'cp2', 'cp3', 'csp', 'cst', 'dd1', 'dd2', 'ddc', 'ddd', 'dde', 'ddf', 'ddg', 'ddh', 'ddi', 'ddj', 'ddk', 'ddl', 'ddm', 'ddn', 'ddo', 'ddp', 'ddq', 'ddr', 'dds', 'ddt', 'ddu', 'dgm', 'dis', 'dka', 'dkm', 'dom', 'dpa', 'drb', 'drk', 'dst', 'dtk', 'dvd', 'e01', 'e02', 'ema', 'emn', 'eve', 'evg', 'exo', 'exp', 'f01', 'f02', 'f03', 'f04', 'f05', 'f06', 'f07', 'f08', 'f09', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'fbb', 'fem', 'fnm', 'frf', 'fut', 'g00', 'g01', 'g02', 'g03', 'g04', 'g05', 'g06', 'g07', 'g08', 'g09', 'g10', 'g11', 'g17', 'g18', 'g99', 'gk1', 'gk2', 'gnt', 'gpt', 'grn', 'gs1', 'gtc', 'gvl', 'h09', 'h17', 'hho', 'hml', 'hop', 'hou', 'htr', 'htr17', 'ice', 'ima', 'inv', 'isd', 'itp', 'j12', 'j13', 'j14', 'j15', 'j16', 'j17', 'j18', 'j19', 'jgp', 'jou', 'jud', 'jvc', 'kld', 'ktk', 'l12', 'l13', 'l14', 'l15', 'l16', 'l17', 'lea', 'leb', 'leg', 'lgn', 'lrw', 'm10', 'm11', 'm12', 'm13', 'm14', 'm15', 'm19', 'm20', 'mbs', 'md1', 'me1', 'me2', 'me3', 'me4', 'med', 'mgb', 'mh1', 'mir', 'mm2', 'mm3', 'mma', 'mmq', 'mor', 'mp2', 'mpr', 'mps', 'mrd', 'nem', 'nph', 'oarc', 'oc13', 'oc14', 'oc15', 'oc16', 'oc17', 'oc18', 'ocm1', 'ocmd', 'ody', 'oe01', 'ogw', 'ohop', 'olgc', 'ons', 'opc2', 'opca', 'ori', 'ovnt', 'p02', 'p03', 'p04', 'p05', 'p06', 'p07', 'p08', 'p09', 'p10', 'p10e', 'p11', 'p15a', 'p2hg', 'paer', 'pakh', 'pal00', 'pal01', 'pal02', 'pal03', 'pal04', 'pal05', 'pal06', 'pal99', 'palp', 'pana', 'parc', 'parl', 'pavr', 'pbbd', 'pbfz', 'pbng', 'pbok', 'pc2', 'pca', 'pcel', 'pcmd', 'pcmp', 'pcy', 'pd2', 'pd3', 'pdgm', 'pdka', 'pdom', 'pdp10', 'pdp11', 'pdp12', 'pdp13', 'pdp14', 'pdrc', 'pdtk', 'pdtp', 'pelp', 'pemn', 'pf19', 'pfrf', 'pg07', 'pg08', 'pgpx', 'pgrn', 'pgru', 'pgtc', 'pgtw', 'phel', 'phj', 'phop', 'phou', 'phpr', 'phuk', 'pi13', 'pi14', 'pidw', 'pisd', 'pjas', 'pjjt', 'pjou', 'pjse', 'pkld', 'pktk', 'plc', 'plgm', 'plny', 'plpa', 'pls', 'pm10', 'pm11', 'pm12', 'pm13', 'pm14', 'pm15', 'pm19', 'pmbs', 'pmei', 'pmh1', 'pmoa', 'pmps', 'pmps06', 'pmps07', 'pmps08', 'pmps09', 'pmps10', 'pmps11', 'pnat', 'pnph', 'pogw', 'por', 'pori', 'ppc1', 'ppod', 'ppre', 'ppro', 'pr2', 'pred', 'prel', 'pres', 'prix', 'prm', 'prna', 'proe', 'prtr', 'prw2', 'prwk', 'ps11', 'ps14', 'ps15', 'ps16', 'ps17', 'ps18', 'psal', 'psdc', 'psoi', 'psom', 'pss1', 'pss2', 'pss3', 'psum', 'psus', 'ptc', 'pths', 'ptk', 'ptkdf', 'puma', 'purl', 'pust', 'pvan', 'pwar', 'pwcq', 'pwor', 'pwos', 'pwp09', 'pwp10', 'pwp11', 'pwp12', 'pwpn', 'pwwk', 'pxln', 'pxtc', 'pz1', 'pz2', 'pzen', 'rav', 'ren', 'rin', 'rix', 'rna', 'roe', 'rqs', 'rtr', 's00', 's99', 'scg', 'shm', 'soi', 'sok', 'som', 'ss1', 'ss2', 'sth', 'sum', 'tbth', 'td0', 'td2', 'tdag', 'tfth', 'thp1', 'thp2', 'thp3', 'ths', 'tmp', 'tor', 'tpr', 'tsb', 'tsp', 'uds', 'ugin', 'ugl', 'ulg', 'uma', 'unh', 'usg', 'ust', 'v09', 'v10', 'v11', 'v12', 'v13', 'v14', 'v15', 'v16', 'v17', 'vis', 'vma', 'w16', 'w17', 'war', 'wc00', 'wc01', 'wc02', 'wc03', 'wc04', 'wc97', 'wc98', 'wc99', 'wth', 'wwk', 'xln', 'zen']
[INFO] 2019-06-13 08:41:30,521: Downloading set 10e information
[INFO] 2019-06-13 08:41:30,524: Downloaded: https://api.scryfall.com/sets/10e (Cache = True)
[INFO] 2019-06-13 08:41:30,524: Downloading page 1 of card data for 10e
[INFO] 2019-06-13 08:41:30,532: Downloaded: https://api.scryfall.com/cards/search?order=set&q=e%3A10e&unique=prints (Cache = True)
[INFO] 2019-06-13 08:41:30,532: Downloading page 2 of card data for 10e
[INFO] 2019-06-13 08:41:30,540: Downloaded: https://api.scryfall.com/cards/search?format=json&include_extras=false&include_multilingual=false&order=set&page=2&q=e%3A10e&unique=prints (Cache = True)
[INFO] 2019-06-13 08:41:30,540: Downloading page 3 of card data for 10e
[INFO] 2019-06-13 08:41:30,548: Downloaded: https://api.scryfall.com/cards/search?format=json&include_extras=false&include_multilingual=false&order=set&page=3&q=e%3A10e&unique=prints (Cache = True)
[INFO] 2019-06-13 08:41:30,548: Downloading page 1 of card data for 10e
[INFO] 2019-06-13 08:41:30,800: Downloaded: https://api.scryfall.com/cards/search?q=is%3Avariation%20set%3A10e (Cache = False)
[INFO] 2019-06-13 08:41:30,805: Downloaded: https://api.scryfall.com/sets/10e (Cache = True)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kylehankinson/Code/MTG/mtgjson/mtgjson4/__main__.py", line 191, in <module>
    main()
  File "/Users/kylehankinson/Code/MTG/mtgjson/mtgjson4/__main__.py", line 165, in main
    compiled = compile_mtg.build_output_file(sf_set, set_code, args.skip_keys)
  File "/Users/kylehankinson/Code/MTG/mtgjson/mtgjson4/compile_mtg.py", line 60, in build_output_file
    mkm_resp = MKM_API.get().market_place.expansions(game=1)
  File "/usr/local/lib/python3.7/site-packages/mkmsdk/mkm.py", line 43, in __call__
    return self.resolver.resolve(api_map=self.api_map, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mkmsdk/resolvers.py", line 61, in resolve
    return self.api.request(url=self.url, method=self.method, data=data, params=params)
  File "/usr/local/lib/python3.7/site-packages/mkmsdk/api.py", line 39, in request
    return self.handle_response(response)
  File "/usr/local/lib/python3.7/site-packages/mkmsdk/api.py", line 95, in handle_response
    raise exceptions.ConnectionError(response)
mkmsdk.exceptions.ConnectionError: Request failed
Status code: 403
Response message: Forbidden
b''

```

I'm using Python 3.7.3.

**Comment by ZeldaZach** [comment]
You don't have any partner keys, so you'll want to pass the `--skip-keys` flag to any and all builds you make. I'll see about making it more explicit

**Comment by hankinsoft** [comment]
Thanks, adding `--skip-keys` let the script continue.
