### ISSUE TITLE
Scrape to update Dinosaurs and Planeswalkers.

### ISSUE THREAD

**Issue by Psithief** [mtgjson/mtgjson#465]
* 13 cards received errata to add the Dinosaur subtype.
* All planeswalker cards have the super-type Legendary now.

**Comment by fenhl** [comment]
Getting the following error while rebuilding:

```
$ node build/buildLang all allsets
10E:de
Processing 383 cards
Processing 368 multiverseids
Doing set corrections...
TypeError: Cannot read property 'concat' of undefined
    at /opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:285:38
    at Array.forEach (native)
    at /opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:244:10
    at Array.forEach (native)
    at Object.exports.performSetCorrections (/opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:202:17)
    at Function.processCards (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:156:11)
    at Immediate.next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:51:22)
    at runCallback (timers.js:676:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:21
                                throw args[0];
                                ^

TypeError: Cannot read property 'concat' of undefined
    at /opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:285:38
    at Array.forEach (native)
    at /opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:244:10
    at Array.forEach (native)
    at Object.exports.performSetCorrections (/opt/git/github.com/fenhl/mtgjson/stage/shared/shared.js:202:17)
    at Function.processCards (/opt/git/github.com/fenhl/mtgjson/stage/build/buildLang.js:156:11)
    at Immediate.next (/opt/git/github.com/fenhl/mtgjson/stage/node_modules/tiptoe/index.js:51:22)
    at runCallback (timers.js:676:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by tooomm** [comment]
How did you deal with that error for your recent build @DanielHeath?

**Comment by Psithief** [comment]
It looks like nobody checked that there's at least one printing scraped from the source before applying corrections.

https://github.com/mtgjson/mtgjson/blob/ac7d3bb0d33c1c1262386dc7df38f537f22a042f/shared/shared.js#L285

You might want to add a `if(!card.printings) card.printings = [];` in the line before.

**Comment by DanielHeath** [comment]
I didn't get the error when I ran it

**Comment by ZeldaZach** [comment]
Done via #471
