### ISSUE TITLE
SQLLiteFile is empty

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#758]
#### Version(s) affected
- [ ] MTGJSON 4
- [X] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0+20200703

#### Description of Bug
The SQLLite File in https://mtgjson.com/api/v5/AllPrintings.sqlite is empty.

**Comment by splatterb0y** [comment]
This is also true for the regular SQL files.

**Comment by patricklewis** [comment]
After discovering that https://mtgjson.com/api/v5/AllPrintings.sqlite had no data this morning I tried building my own sqlite file with [mtgsqlive](https://github.com/mtgjson/mtgsqlive) and encountered an error:

```
❯ python3 -m mtgsqlive -i ~/Downloads/AllPrintings.json -o output.sqlite
[INFO] 2021-01-20 10:52:13,818: Loading json file into memory
[INFO] 2021-01-20 10:52:17,909: Building SQLite schema
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/patrick/Projects/mtgsqlive/mtgsqlive/__main__.py", line 79, in <module>
    json2sql.execute(input_file, output_file, args.x, args.e)
  File "/Users/patrick/Projects/mtgsqlive/mtgsqlive/json2sql.py", line 33, in execute
    build_sql_schema(json_data, output_file, engine)
  File "/Users/patrick/Projects/mtgsqlive/mtgsqlive/json2sql.py", line 130, in build_sql_schema
    cursor.executescript(schema)
sqlite3.OperationalError: near "INDEX": syntax error
```

**Comment by ZeldaZach** [comment]
I've reverted the breaking change upstream, and we'll have a new build of this file up today. Sorry for that issue.
